name = "chillax-corner"
main = "server.js"
workers_dev = true
compatibility_date = "2025-08-15" # Use a recent compatibility date
# Crucial step for Node.js APIs
compatibility_flags = [
  "nodejs_compat",
  "enable_nodejs_http_modules",
  "enable_nodejs_http_server_modules",
  "experimental" # May be required for newer features
]
